"use client";

import {
  BadgeCheck,
  Bell,
  CalendarCheck,
  Cannabis,
  ChevronRight,
  ChevronsUpDown,
  Clipboard,
  CreditCard,
  Folder,
  Forward,
  Leaf,
  LogOut,
  MoreHorizontal,
  PencilRuler,
  Plus,
  Settings,
  Sparkles,
  Sprout,
  Thermometer,
  Trash2,
  TreeDeciduous,
  Users,
  Workflow,
} from "lucide-react";

import { Avatar, AvatarFallback, AvatarImage } from "~/components/ui/avatar";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "~/components/ui/breadcrumb";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "~/components/ui/collapsible";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuTrigger,
} from "~/components/ui/dropdown-menu";
import { Separator } from "~/components/ui/separator";
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuAction,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
  SidebarRail,
  SidebarTrigger,
} from "~/components/ui/sidebar";

// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "~/components/theme-provider";
import { SidebarProvider, SidebarInset } from "~/components/ui/sidebar";
import { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// This is sample data.
const data = {
  user: {
    name: "grower_user", // Placeholder user
    email: "grower@example.com",
    avatar: "/avatars/grower.jpg", // Example avatar
  },
  teams: [
    {
      name: "GrowAGram Collective", // A community or team of growers
      logo: Leaf, // Icon for cannabis
      plan: "Premium", // GrowAGram plan (could have different tiers)
    },
    {
      name: "Personal Growers", // Individual growers could have "teams"
      logo: TreeDeciduous,
      plan: "Basic",
    },
  ],
  navMain: [
    {
      title: "Grows",
      url: "#",
      icon: Cannabis, // An icon representing plants or growth
      isActive: true,
      items: [
        {
          title: "My Grows", // View and manage their cannabis grows
          url: "#",
        },
        {
          title: "Create New Grow", // Easily add new grows
          url: "#",
        },
        {
          title: "Grow History", // Check history of completed grows
          url: "#",
        },
      ],
    },
    {
      title: "Plants",
      url: "#",
      icon: Sprout, // Icon representing individual plants
      items: [
        {
          title: "All Plants", // View and manage all plants within grows
          url: "#",
        },
        {
          title: "Add Plant", // Easily add new plants to a grow
          url: "#",
        },
        {
          title: "Plant Details", // Check detailed info about plants
          url: "#",
        },
      ],
    },
    {
      title: "Updates & Posts",
      url: "#",
      icon: Clipboard, // Icon for updates, posts, or activity feed
      items: [
        {
          title: "All Updates", // View and manage updates on grows
          url: "#",
        },
        {
          title: "Add Update", // Add an update (watering, pruning, etc.)
          url: "#",
        },
        {
          title: "Ask Question", // Ask the community or other growers
          url: "#",
        },
      ],
    },
    {
      title: "Inventory",
      url: "#",
      icon: PencilRuler, // Icon representing inventory or tools
      items: [
        {
          title: "My Inventory", // Manage seeds, tools, LEDs, etc.
          url: "#",
        },
        {
          title: "Add Item", // Add an item to the inventory
          url: "#",
        },
        {
          title: "Item Categories", // Manage item categories (e.g., seeds, tools)
          url: "#",
        },
      ],
    },
    {
      title: "Community",
      url: "#",
      icon: Users, // Icon for community or collaboration
      items: [
        {
          title: "Discussions", // Community forum discussions
          url: "#",
        },
        {
          title: "Guides & Tips", // Guides shared by other growers
          url: "#",
        },
        {
          title: "Events", // Grow-related events and meetups
          url: "#",
        },
      ],
    },
    {
      title: "Settings",
      url: "#",
      icon: Settings, // Icon for settings
      items: [
        {
          title: "Account Settings", // Manage user profile, billing, etc.
          url: "#",
        },
        {
          title: "Team Management", // Manage team members if part of a collective
          url: "#",
        },
        {
          title: "Notifications", // Manage notifications and alerts
          url: "#",
        },
        {
          title: "Subscription", // View or upgrade subscription
          url: "#",
        },
      ],
    },
  ],
  projects: [
    {
      name: "Grow Automation",
      url: "#",
      icon: Workflow, // Icon representing automation
    },
    {
      name: "Nutrient Scheduling",
      url: "#",
      icon: CalendarCheck, // Icon for scheduling or feeding plans
    },
    {
      name: "Climate Control",
      url: "#",
      icon: Thermometer, // Icon for temperature and climate control
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [activeTeam, setActiveTeam] = useState(data.teams[0]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <Sidebar collapsible="icon">
              <SidebarHeader>
                <SidebarMenu>
                  <SidebarMenuItem>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <SidebarMenuButton
                          size="lg"
                          className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
                        >
                          <div className="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
                            <activeTeam.logo className="size-4" />
                          </div>
                          <div className="grid flex-1 text-left text-sm leading-tight">
                            <span className="truncate font-semibold">
                              {activeTeam.name}
                            </span>
                            <span className="truncate text-xs">
                              {activeTeam.plan}
                            </span>
                          </div>
                          <ChevronsUpDown className="ml-auto" />
                        </SidebarMenuButton>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent
                        className="w-[--radix-dropdown-menu-trigger-width] min-w-56 rounded-lg"
                        align="start"
                        side="bottom"
                        sideOffset={4}
                      >
                        <DropdownMenuLabel className="text-xs text-muted-foreground">
                          Teams
                        </DropdownMenuLabel>
                        {data.teams.map((team, index) => (
                          <DropdownMenuItem
                            key={team.name}
                            onClick={() => setActiveTeam(team)}
                            className="gap-2 p-2"
                          >
                            <div className="flex size-6 items-center justify-center rounded-sm border">
                              <team.logo className="size-4 shrink-0" />
                            </div>
                            {team.name}
                            <DropdownMenuShortcut>
                              ⌘{index + 1}
                            </DropdownMenuShortcut>
                          </DropdownMenuItem>
                        ))}
                        <DropdownMenuSeparator />
                        <DropdownMenuItem className="gap-2 p-2">
                          <div className="flex size-6 items-center justify-center rounded-md border bg-background">
                            <Plus className="size-4" />
                          </div>
                          <div className="font-medium text-muted-foreground">
                            Add team
                          </div>
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </SidebarMenuItem>
                </SidebarMenu>
              </SidebarHeader>
              <SidebarContent>
                <SidebarGroup>
                  <SidebarGroupLabel>Platform</SidebarGroupLabel>
                  <SidebarMenu>
                    {data.navMain.map((item) => (
                      <Collapsible
                        key={item.title}
                        asChild
                        defaultOpen={item.isActive}
                        className="group/collapsible"
                      >
                        <SidebarMenuItem>
                          <CollapsibleTrigger asChild>
                            <SidebarMenuButton tooltip={item.title}>
                              {item.icon && <item.icon />}
                              <span>{item.title}</span>
                              <ChevronRight className="ml-auto transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90" />
                            </SidebarMenuButton>
                          </CollapsibleTrigger>
                          <CollapsibleContent>
                            <SidebarMenuSub>
                              {item.items?.map((subItem) => (
                                <SidebarMenuSubItem key={subItem.title}>
                                  <SidebarMenuSubButton asChild>
                                    <a href={subItem.url}>
                                      <span>{subItem.title}</span>
                                    </a>
                                  </SidebarMenuSubButton>
                                </SidebarMenuSubItem>
                              ))}
                            </SidebarMenuSub>
                          </CollapsibleContent>
                        </SidebarMenuItem>
                      </Collapsible>
                    ))}
                  </SidebarMenu>
                </SidebarGroup>
                <SidebarGroup className="group-data-[collapsible=icon]:hidden">
                  <SidebarGroupLabel>Projects</SidebarGroupLabel>
                  <SidebarMenu>
                    {data.projects.map((item) => (
                      <SidebarMenuItem key={item.name}>
                        <SidebarMenuButton asChild>
                          <a href={item.url}>
                            <item.icon />
                            <span>{item.name}</span>
                          </a>
                        </SidebarMenuButton>
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <SidebarMenuAction showOnHover>
                              <MoreHorizontal />
                              <span className="sr-only">More</span>
                            </SidebarMenuAction>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent
                            className="w-48 rounded-lg"
                            side="bottom"
                            align="end"
                          >
                            <DropdownMenuItem>
                              <Folder className="text-muted-foreground" />
                              <span>View Project</span>
                            </DropdownMenuItem>
                            <DropdownMenuItem>
                              <Forward className="text-muted-foreground" />
                              <span>Share Project</span>
                            </DropdownMenuItem>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem>
                              <Trash2 className="text-muted-foreground" />
                              <span>Delete Project</span>
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </SidebarMenuItem>
                    ))}
                    <SidebarMenuItem>
                      <SidebarMenuButton className="text-sidebar-foreground/70">
                        <MoreHorizontal className="text-sidebar-foreground/70" />
                        <span>More</span>
                      </SidebarMenuButton>
                    </SidebarMenuItem>
                  </SidebarMenu>
                </SidebarGroup>
              </SidebarContent>
              <SidebarFooter>
                <SidebarMenu>
                  <SidebarMenuItem>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <SidebarMenuButton
                          size="lg"
                          className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
                        >
                          <Avatar className="h-8 w-8 rounded-lg">
                            <AvatarImage
                              src={data.user.avatar}
                              alt={data.user.name}
                            />
                            <AvatarFallback className="rounded-lg">
                              CN
                            </AvatarFallback>
                          </Avatar>
                          <div className="grid flex-1 text-left text-sm leading-tight">
                            <span className="truncate font-semibold">
                              {data.user.name}
                            </span>
                            <span className="truncate text-xs">
                              {data.user.email}
                            </span>
                          </div>
                          <ChevronsUpDown className="ml-auto size-4" />
                        </SidebarMenuButton>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent
                        className="w-[--radix-dropdown-menu-trigger-width] min-w-56 rounded-lg"
                        side="bottom"
                        align="end"
                        sideOffset={4}
                      >
                        <DropdownMenuLabel className="p-0 font-normal">
                          <div className="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
                            <Avatar className="h-8 w-8 rounded-lg">
                              <AvatarImage
                                src={data.user.avatar}
                                alt={data.user.name}
                              />
                              <AvatarFallback className="rounded-lg">
                                CN
                              </AvatarFallback>
                            </Avatar>
                            <div className="grid flex-1 text-left text-sm leading-tight">
                              <span className="truncate font-semibold">
                                {data.user.name}
                              </span>
                              <span className="truncate text-xs">
                                {data.user.email}
                              </span>
                            </div>
                          </div>
                        </DropdownMenuLabel>
                        <DropdownMenuSeparator />
                        <DropdownMenuGroup>
                          <DropdownMenuItem>
                            <Sparkles />
                            Upgrade to Pro
                          </DropdownMenuItem>
                        </DropdownMenuGroup>
                        <DropdownMenuSeparator />
                        <DropdownMenuGroup>
                          <DropdownMenuItem>
                            <BadgeCheck />
                            Account
                          </DropdownMenuItem>
                          <DropdownMenuItem>
                            <CreditCard />
                            Billing
                          </DropdownMenuItem>
                          <DropdownMenuItem>
                            <Bell />
                            Notifications
                          </DropdownMenuItem>
                        </DropdownMenuGroup>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem>
                          <LogOut />
                          Log out
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </SidebarMenuItem>
                </SidebarMenu>
              </SidebarFooter>
              <SidebarRail />
            </Sidebar>
            <SidebarInset>
              <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                <div className="flex items-center gap-2 px-4">
                  <SidebarTrigger className="-ml-1" />
                  <Separator orientation="vertical" className="mr-2 h-4" />
                  <Breadcrumb>
                    <BreadcrumbList>
                      <BreadcrumbItem className="hidden md:block">
                        <BreadcrumbLink href="#">
                          Building Your Application
                        </BreadcrumbLink>
                      </BreadcrumbItem>
                      <BreadcrumbSeparator className="hidden md:block" />
                      <BreadcrumbItem>
                        <BreadcrumbPage>Data Fetching</BreadcrumbPage>
                      </BreadcrumbItem>
                    </BreadcrumbList>
                  </Breadcrumb>
                </div>
              </header>
              <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
                <div className="grid auto-rows-min gap-4 md:grid-cols-3">
                  <div className="aspect-video rounded-xl bg-muted/50" />
                  <div className="aspect-video rounded-xl bg-muted/50" />
                  <div className="aspect-video rounded-xl bg-muted/50" />
                </div>
                <div className="min-h-[100vh] flex-1 rounded-xl bg-muted/50 md:min-h-min">
                  {children}
                </div>
              </div>
            </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
